tabWidth: 4
semi: true
singleQuote: true
printWidth: 90
importOrder:
  [
    '^virtual:',
    "^[a-z]",
    '^@\w',
    '^@/',
    '^\.{2}/',
    '^\./',
    '^~(.*)$',
  ]
importOrderSeparation: true
importOrderSortSpecifiers: true
